// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'profile.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Profile _$ProfileFromJson(Map<String, dynamic> json) => Profile(
      privacyItemUnlimit: json['privacyItemUnlimit'] == null
          ? null
          : PrivacyItemUnlimit.fromJson(
              json['privacyItemUnlimit'] as Map<String, dynamic>),
      avatarDetail: json['avatarDetail'],
      avatarImgIdStr: json['avatarImgIdStr'] as String?,
      backgroundImgIdStr: json['backgroundImgIdStr'] as String?,
      city: json['city'] as int?,
      mutual: json['mutual'] as bool?,
      defaultAvatar: json['defaultAvatar'] as bool?,
      detailDescription: json['detailDescription'] as String?,
      vipType: json['vipType'] as int?,
      followed: json['followed'] as bool?,
      createTime: json['createTime'] as int?,
      remarkName: json['remarkName'],
      authStatus: json['authStatus'] as int?,
      expertTags: json['expertTags'],
      avatarImgId: json['avatarImgId'] as int?,
      birthday: json['birthday'] as int?,
      gender: json['gender'] as int?,
      nickname: json['nickname'] as String?,
      avatarUrl: json['avatarUrl'] as String?,
      backgroundImgId: json['backgroundImgId'] as int?,
      backgroundUrl: json['backgroundUrl'] as String?,
      userType: json['userType'] as int?,
      accountStatus: json['accountStatus'] as int?,
      province: json['province'] as int?,
      djStatus: json['djStatus'] as int?,
      description: json['description'] as String?,
      userId: json['userId'] as int?,
      signature: json['signature'] as String?,
      authority: json['authority'] as int?,
      followeds: json['followeds'] as int?,
      follows: json['follows'] as int?,
      blacklist: json['blacklist'] as bool?,
      eventCount: json['eventCount'] as int?,
      allSubscribedCount: json['allSubscribedCount'] as int?,
      playlistBeSubscribedCount: json['playlistBeSubscribedCount'] as int?,
      followTime: json['followTime'],
      followMe: json['followMe'] as bool?,
      artistIdentity: json['artistIdentity'] as List<dynamic>?,
      cCount: json['cCount'] as int?,
      inBlacklist: json['inBlacklist'] as bool?,
      sDjpCount: json['sDJPCount'] as int?,
      playlistCount: json['playlistCount'] as int?,
      sCount: json['sCount'] as int?,
      newFollows: json['newFollows'] as int?,
    );

Map<String, dynamic> _$ProfileToJson(Profile instance) => <String, dynamic>{
      'privacyItemUnlimit': instance.privacyItemUnlimit,
      'avatarDetail': instance.avatarDetail,
      'avatarImgIdStr': instance.avatarImgIdStr,
      'backgroundImgIdStr': instance.backgroundImgIdStr,
      'city': instance.city,
      'mutual': instance.mutual,
      'defaultAvatar': instance.defaultAvatar,
      'detailDescription': instance.detailDescription,
      'vipType': instance.vipType,
      'followed': instance.followed,
      'createTime': instance.createTime,
      'remarkName': instance.remarkName,
      'authStatus': instance.authStatus,
      'expertTags': instance.expertTags,
      'avatarImgId': instance.avatarImgId,
      'birthday': instance.birthday,
      'gender': instance.gender,
      'nickname': instance.nickname,
      'avatarUrl': instance.avatarUrl,
      'backgroundImgId': instance.backgroundImgId,
      'backgroundUrl': instance.backgroundUrl,
      'userType': instance.userType,
      'accountStatus': instance.accountStatus,
      'province': instance.province,
      'djStatus': instance.djStatus,
      'description': instance.description,
      'userId': instance.userId,
      'signature': instance.signature,
      'authority': instance.authority,
      'followeds': instance.followeds,
      'follows': instance.follows,
      'blacklist': instance.blacklist,
      'eventCount': instance.eventCount,
      'allSubscribedCount': instance.allSubscribedCount,
      'playlistBeSubscribedCount': instance.playlistBeSubscribedCount,
      'followTime': instance.followTime,
      'followMe': instance.followMe,
      'artistIdentity': instance.artistIdentity,
      'cCount': instance.cCount,
      'inBlacklist': instance.inBlacklist,
      'sDJPCount': instance.sDjpCount,
      'playlistCount': instance.playlistCount,
      'sCount': instance.sCount,
      'newFollows': instance.newFollows,
    };
