// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'playlist.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Playlist _$PlaylistFromJson(Map<String, dynamic> json) => Playlist(
      subscribers: json['subscribers'] as List<dynamic>?,
      subscribed: json['subscribed'] as bool?,
      creator: json['creator'] == null
          ? null
          : Creator.fromJson(json['creator'] as Map<String, dynamic>),
      artists: json['artists'],
      tracks: json['tracks'],
      top: json['top'] as bool?,
      updateFrequency: json['updateFrequency'],
      backgroundCoverId: json['backgroundCoverId'] as int?,
      backgroundCoverUrl: json['backgroundCoverUrl'],
      titleImage: json['titleImage'] as int?,
      titleImageUrl: json['titleImageUrl'],
      englishTitle: json['englishTitle'],
      opRecommend: json['opRecommend'] as bool?,
      recommendInfo: json['recommendInfo'],
      subscribedCount: json['subscribedCount'] as int?,
      cloudTrackCount: json['cloudTrackCount'] as int?,
      userId: json['userId'] as int?,
      totalDuration: json['totalDuration'] as int?,
      coverImgId: json['coverImgId'] as int?,
      privacy: json['privacy'] as int?,
      trackUpdateTime: json['trackUpdateTime'] as int?,
      trackCount: json['trackCount'] as int?,
      updateTime: json['updateTime'] as int?,
      commentThreadId: json['commentThreadId'] as String?,
      coverImgUrl: json['coverImgUrl'] as String?,
      specialType: json['specialType'] as int?,
      anonimous: json['anonimous'] as bool?,
      createTime: json['createTime'] as int?,
      highQuality: json['highQuality'] as bool?,
      newImported: json['newImported'] as bool?,
      trackNumberUpdateTime: json['trackNumberUpdateTime'] as int?,
      playCount: json['playCount'] as int?,
      adType: json['adType'] as int?,
      description: json['description'] as String?,
      tags: (json['tags'] as List<dynamic>?)?.map((e) => e as String).toList(),
      ordered: json['ordered'] as bool?,
      status: json['status'] as int?,
      name: json['name'] as String?,
      id: json['id'] as int?,
      coverImgIdStr: json['coverImgId_str'] as String?,
      sharedUsers: json['sharedUsers'],
      shareStatus: json['shareStatus'],
      copied: json['copied'] as bool?,
    );

Map<String, dynamic> _$PlaylistToJson(Playlist instance) => <String, dynamic>{
      'subscribers': instance.subscribers,
      'subscribed': instance.subscribed,
      'creator': instance.creator,
      'artists': instance.artists,
      'tracks': instance.tracks,
      'top': instance.top,
      'updateFrequency': instance.updateFrequency,
      'backgroundCoverId': instance.backgroundCoverId,
      'backgroundCoverUrl': instance.backgroundCoverUrl,
      'titleImage': instance.titleImage,
      'titleImageUrl': instance.titleImageUrl,
      'englishTitle': instance.englishTitle,
      'opRecommend': instance.opRecommend,
      'recommendInfo': instance.recommendInfo,
      'subscribedCount': instance.subscribedCount,
      'cloudTrackCount': instance.cloudTrackCount,
      'userId': instance.userId,
      'totalDuration': instance.totalDuration,
      'coverImgId': instance.coverImgId,
      'privacy': instance.privacy,
      'trackUpdateTime': instance.trackUpdateTime,
      'trackCount': instance.trackCount,
      'updateTime': instance.updateTime,
      'commentThreadId': instance.commentThreadId,
      'coverImgUrl': instance.coverImgUrl,
      'specialType': instance.specialType,
      'anonimous': instance.anonimous,
      'createTime': instance.createTime,
      'highQuality': instance.highQuality,
      'newImported': instance.newImported,
      'trackNumberUpdateTime': instance.trackNumberUpdateTime,
      'playCount': instance.playCount,
      'adType': instance.adType,
      'description': instance.description,
      'tags': instance.tags,
      'ordered': instance.ordered,
      'status': instance.status,
      'name': instance.name,
      'id': instance.id,
      'coverImgId_str': instance.coverImgIdStr,
      'sharedUsers': instance.sharedUsers,
      'shareStatus': instance.shareStatus,
      'copied': instance.copied,
    };
