// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'find_top.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

FindTop _$FindTopFromJson(Map<String, dynamic> json) => FindTop(
      subscribers: json['subscribers'] as List<dynamic>?,
      subscribed: json['subscribed'],
      creator: json['creator'],
      artists: json['artists'],
      tracks: json['tracks'],
      updateFrequency: json['updateFrequency'] as String?,
      backgroundCoverId: json['backgroundCoverId'] as int?,
      backgroundCoverUrl: json['backgroundCoverUrl'],
      titleImage: json['titleImage'] as int?,
      coverText: json['coverText'],
      titleImageUrl: json['titleImageUrl'],
      coverImageUrl: json['coverImageUrl'],
      iconImageUrl: json['iconImageUrl'],
      englishTitle: json['englishTitle'],
      opRecommend: json['opRecommend'] as bool?,
      recommendInfo: json['recommendInfo'],
      socialPlaylistCover: json['socialPlaylistCover'],
      tsSongCount: json['tsSongCount'] as int?,
      adType: json['adType'] as int?,
      trackNumberUpdateTime: json['trackNumberUpdateTime'] as int?,
      subscribedCount: json['subscribedCount'] as int?,
      cloudTrackCount: json['cloudTrackCount'] as int?,
      trackUpdateTime: json['trackUpdateTime'] as int?,
      playCount: json['playCount'] as int?,
      updateTime: json['updateTime'] as int?,
      specialType: json['specialType'] as int?,
      coverImgId: json['coverImgId'] as int?,
      anonimous: json['anonimous'] as bool?,
      trackCount: json['trackCount'] as int?,
      commentThreadId: json['commentThreadId'] as String?,
      privacy: json['privacy'] as int?,
      newImported: json['newImported'] as bool?,
      totalDuration: json['totalDuration'] as int?,
      coverImgUrl: json['coverImgUrl'] as String?,
      highQuality: json['highQuality'] as bool?,
      createTime: json['createTime'] as int?,
      ordered: json['ordered'] as bool?,
      description: json['description'] as String?,
      status: json['status'] as int?,
      tags: json['tags'] as List<dynamic>?,
      userId: json['userId'] as int?,
      name: json['name'] as String?,
      id: json['id'] as int?,
      coverImgIdStr: json['coverImgId_str'] as String?,
      toplistType: json['ToplistType'] as String?,
    );

Map<String, dynamic> _$FindTopToJson(FindTop instance) => <String, dynamic>{
      'subscribers': instance.subscribers,
      'subscribed': instance.subscribed,
      'creator': instance.creator,
      'artists': instance.artists,
      'tracks': instance.tracks,
      'updateFrequency': instance.updateFrequency,
      'backgroundCoverId': instance.backgroundCoverId,
      'backgroundCoverUrl': instance.backgroundCoverUrl,
      'titleImage': instance.titleImage,
      'coverText': instance.coverText,
      'titleImageUrl': instance.titleImageUrl,
      'coverImageUrl': instance.coverImageUrl,
      'iconImageUrl': instance.iconImageUrl,
      'englishTitle': instance.englishTitle,
      'opRecommend': instance.opRecommend,
      'recommendInfo': instance.recommendInfo,
      'socialPlaylistCover': instance.socialPlaylistCover,
      'tsSongCount': instance.tsSongCount,
      'adType': instance.adType,
      'trackNumberUpdateTime': instance.trackNumberUpdateTime,
      'subscribedCount': instance.subscribedCount,
      'cloudTrackCount': instance.cloudTrackCount,
      'trackUpdateTime': instance.trackUpdateTime,
      'playCount': instance.playCount,
      'updateTime': instance.updateTime,
      'specialType': instance.specialType,
      'coverImgId': instance.coverImgId,
      'anonimous': instance.anonimous,
      'trackCount': instance.trackCount,
      'commentThreadId': instance.commentThreadId,
      'privacy': instance.privacy,
      'newImported': instance.newImported,
      'totalDuration': instance.totalDuration,
      'coverImgUrl': instance.coverImgUrl,
      'highQuality': instance.highQuality,
      'createTime': instance.createTime,
      'ordered': instance.ordered,
      'description': instance.description,
      'status': instance.status,
      'tags': instance.tags,
      'userId': instance.userId,
      'name': instance.name,
      'id': instance.id,
      'coverImgId_str': instance.coverImgIdStr,
      'ToplistType': instance.toplistType,
    };
